#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors

Monitor panel configuration builder for Gorge Chase.
峡谷追猎监控面板配置构建器。
"""


from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """
    # This function is used to create monitoring panel configurations for custom indicators.
    # 该函数用于创建自定义指标的监控面板配置。
    """
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("峡谷追猎")
        .add_group(
            group_name="算法指标",
            group_name_en="algorithm",
        )
        .add_panel(
            name="累积回报",
            name_en="reward",
            type="line",
        )
        .add_metric(
            metrics_name="reward",
            expr="avg(reward{})",
        )
        .end_panel()
        .add_panel(
            name="总损失",
            name_en="total_loss",
            type="line",
        )
        .add_metric(
            metrics_name="total_loss",
            expr="avg(total_loss{})",
        )
        .end_panel()
        .add_panel(
            name="价值损失",
            name_en="value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="value_loss",
            expr="avg(value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="策略损失",
            name_en="policy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="policy_loss",
            expr="avg(policy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="熵损失",
            name_en="entropy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="entropy_loss",
            expr="avg(entropy_loss{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            name="对局结果占比",
            name_en="episode_result",
            type="line",
        )
        .add_metric(
            metrics_name="result_win",
            expr="avg(result_win{})",
        )
        .add_metric(
            metrics_name="result_fail",
            expr="avg(result_fail{})",
        )
        .add_metric(
            metrics_name="result_abnormal",
            expr="avg(result_abnormal{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="奖励分项",
            group_name_en="reward_decomposition",
        )
        .add_panel(
            name="核心增量项",
            name_en="reward_core",
            type="line",
        )
        .add_metric(
            metrics_name="score_reward_mean",
            expr="avg(score_reward_mean{})",
        )
        .add_metric(
            metrics_name="step_gain_mean",
            expr="avg(step_gain_mean{})",
        )
        .add_metric(
            metrics_name="treasure_gain_mean",
            expr="avg(treasure_gain_mean{})",
        )
        .end_panel()
        .add_panel(
            name="塑形与风险项",
            name_en="reward_shaping_risk",
            type="line",
        )
        .add_metric(
            metrics_name="dist_shaping_mean",
            expr="avg(dist_shaping_mean{})",
        )
        .add_metric(
            metrics_name="treasure_approach_mean",
            expr="avg(treasure_approach_mean{})",
        )
        .add_metric(
            metrics_name="danger_penalty_mean",
            expr="avg(danger_penalty_mean{})",
        )
        .add_metric(
            metrics_name="double_pressure_penalty_mean",
            expr="avg(double_pressure_penalty_mean{})",
        )
        .end_panel()
        .add_panel(
            name="闪现与终局项",
            name_en="reward_flash_terminal",
            type="line",
        )
        .add_metric(
            metrics_name="flash_reward_mean",
            expr="avg(flash_reward_mean{})",
        )
        .add_metric(
            metrics_name="flash_penalty_mean",
            expr="avg(flash_penalty_mean{})",
        )
        .add_metric(
            metrics_name="invalid_move_penalty_mean",
            expr="avg(invalid_move_penalty_mean{})",
        )
        .add_metric(
            metrics_name="terminal_reward",
            expr="avg(terminal_reward{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="特征可见性",
            group_name_en="feature_visibility",
        )
        .add_panel(
            name="目标可见率",
            name_en="target_visibility",
            type="line",
        )
        .add_metric(
            metrics_name="feat_treasure_visible_rate",
            expr="avg(feat_treasure_visible_rate{})",
        )
        .add_metric(
            metrics_name="feat_buff_visible_rate",
            expr="avg(feat_buff_visible_rate{})",
        )
        .add_metric(
            metrics_name="feat_second_exists_rate",
            expr="avg(feat_second_exists_rate{})",
        )
        .end_panel()
        .add_panel(
            name="资源距离均值",
            name_en="target_distance",
            type="line",
        )
        .add_metric(
            metrics_name="feat_treasure_dist_mean",
            expr="avg(feat_treasure_dist_mean{})",
        )
        .add_metric(
            metrics_name="feat_buff_dist_mean",
            expr="avg(feat_buff_dist_mean{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="威胁与阶段",
            group_name_en="threat_phase",
        )
        .add_panel(
            name="威胁率",
            name_en="threat_rate",
            type="line",
        )
        .add_metric(
            metrics_name="feat_nearest_danger_rate",
            expr="avg(feat_nearest_danger_rate{})",
        )
        .add_metric(
            metrics_name="feat_double_pressure_rate",
            expr="avg(feat_double_pressure_rate{})",
        )
        .end_panel()
        .add_panel(
            name="阶段覆盖",
            name_en="phase_coverage",
            type="line",
        )
        .add_metric(
            metrics_name="feat_post_speedup_rate",
            expr="avg(feat_post_speedup_rate{})",
        )
        .add_metric(
            metrics_name="feat_speedup_eta_mean",
            expr="avg(feat_speedup_eta_mean{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="策略响应",
            group_name_en="policy_response",
        )
        .add_panel(
            name="闪现行为",
            name_en="flash_behavior",
            type="line",
        )
        .add_metric(
            metrics_name="act_flash_rate",
            expr="avg(act_flash_rate{})",
        )
        .add_metric(
            metrics_name="act_flash_in_danger_rate",
            expr="avg(act_flash_in_danger_rate{})",
        )
        .add_metric(
            metrics_name="act_flash_waste_rate",
            expr="avg(act_flash_waste_rate{})",
        )
        .end_panel()
        .add_panel(
            name="资源推进率",
            name_en="target_approach",
            type="line",
        )
        .add_metric(
            metrics_name="act_treasure_approach_rate",
            expr="avg(act_treasure_approach_rate{})",
        )
        .add_metric(
            metrics_name="act_buff_approach_rate",
            expr="avg(act_buff_approach_rate{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="分阶段结果",
            group_name_en="phase_result",
        )
        .add_panel(
            name="阶段回报",
            name_en="phase_reward",
            type="line",
        )
        .add_metric(
            metrics_name="pre_reward_mean",
            expr="avg(pre_reward_mean{})",
        )
        .add_metric(
            metrics_name="post_reward_mean",
            expr="avg(post_reward_mean{})",
        )
        .end_panel()
        .add_panel(
            name="后期生存",
            name_en="post_survival",
            type="line",
        )
        .add_metric(
            metrics_name="post_steps_mean",
            expr="avg(post_steps_mean{})",
        )
        .add_metric(
            metrics_name="post_terminated_rate",
            expr="avg(post_terminated_rate{})",
        )
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
